[package]
name = "waywire-streamd"
version = "0.0.0"
edition.workspace = true

[dependencies]
waywire-protocol = { workspace = true }

anyhow = { workspace = true }
calloop = { workspace = true }
calloop-wayland-source = { workspace = true }
clap = { workspace = true }
memmap2 = { workspace = true }
nix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
wayland-client = { workspace = true }
wayland-protocols = { workspace = true }
wayland-protocols-misc = { workspace = true }
wayland-protocols-wlr = { workspace = true }
xcursor = { workspace = true }
xkbcommon = { workspace = true }

[lints]
workspace = true
